{% set name = "optimistix" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/optimistix-{{ version }}.tar.gz
  sha256: b5e3ce9e6d111f399269c7565c68125bdf6bae9b8ff6cacf30232231159354ef

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - pip
  run:
    - python >=3.9
    - equinox >=0.11.7
    - lineax >=0.0.6
    - jax >=0.4.28
    - jaxtyping >=0.2.23
    - typing_extensions >=4.5.0

test:
  imports:
    - optimistix
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/patrick-kidger/optimistix
  summary: Nonlinear optimisation in JAX and Equinox.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
